<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fupa_net"
 *
 * Auto generated by Extension Builder 2017-04-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Fupa.net',
    'description' => 'Simple usage of FuPa-widgets from http://www.fupa.net/ for your sports society. You have to register to http://www.fupa.net/.',
    'category' => 'plugin',
    'author' => 'Michael Hübe',
    'author_email' => 'typo3@huebe.it',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
